language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2

cache: bundler

before_install: gem install bundler -v 1.9.4

gemfile:
  - gemfiles/rails_3.x.gemfile
  - gemfiles/rails_4.x.gemfile
  - gemfiles/rails_5.x.gemfile

notifications:
  email:
    on_success: change
    on_failure: always
