language: ruby

rvm:
  - 2.2.2
  - 1.9.3

cache: bundler

before_install: gem install bundler -v 1.9.4

gemfile:
  - gemfiles/rails_3.x.gemfile
  - gemfiles/rails_4.x.gemfile

notifications:
  email:
    on_success: change
    on_failure: always
